onlyBuiltDependencies:
  - ' '
  - '"'
  - ','
  - '['
  - ']'
  - a
  - b
  - d
  - e
  - esbuild
  - h
  - i
  - l
  - p
  - r
  - s
  - sharp
  - u
overrides:
  payload-storage-cloudinary: link:..
